#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int x,y;
cout<<"enter the value of x:";
cin>>x;
cout<<"enter the value of y:";
cin>>y;
cout<<"x > y returns"<<(x>y)<<"\n";
cout<<"x < y returns"<<(x<y)<<"\n";
cout<<"x >= y returns"<<(x>=y)<<"\n";
cout<<"x <= y returns"<<(x<=y)<<"\n";
cout<<"x not equal to y returns"<<(x!=y)<<"\n";
cout<<"x equal to y returns"<<(x==y)<<"\n";
getch();
}


